version: "2.2"
name: $PROJECT_NAME

networks:
  default:
  proxy:
    name: ${PROXY:-proxy}
    external: true

volumes:
  site-database:
  site-public:
  site-private:

services:
  mysql:
    image: public.ecr.aws/unocha/mysql:10.6
    hostname: $PROJECT_NAME-mysql
    container_name: $PROJECT_NAME-mysql
    environment:
      - MYSQL_DB=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASS=$MYSQL_PASS
    volumes:
      - "site-database:/var/lib/mysql:rw"
    networks:
      - default

  drupal:
    image: public.ecr.aws/unocha/$IMAGE_NAME:$IMAGE_TAG
    hostname: $PROJECT_NAME-site
    container_name: $PROJECT_NAME-site
    depends_on:
      - mysql
    volumes:
      - "./shared/settings:/srv/www/shared/settings:ro"
      # Mount composer files.
      - "../composer.json:/srv/www/composer.json:rw"
      - "../composer.lock:/srv/www/composer.lock:rw"
      - "../composer.patches.json:/srv/www/composer.patches.json:rw"
      - "../scripts:/srv/www/scripts:ro"
      # Mount a database directory for import.
      - "../database:/srv/www/database:rw"
      # Mount volumes for the private and public files.
      - "site-public:/srv/www/html/sites/default/files:rw"
      - "site-private:/srv/www/html/sites/default/private:rw"
      # Mount the folders needed for the tests.
      - "../phpcs.xml:/srv/www/phpcs.xml:ro"
      - "../phpunit.xml:/srv/www/phpunit.xml:ro"
      # Mount local custom code.
      - "../html/modules/custom:/srv/www/html/modules/custom:rw"
      - "../html/themes/custom:/srv/www/html/themes/custom:rw"
      # Mount configuration and allow overriding it.
      - "../config:/srv/www/config:rw"
      - "../config_dev:/srv/www/config_dev:rw"
    environment:
      - TERM=xterm
      - ENVIRONMENT=dev
      - NGINX_SERVERNAME=$SITE_DOMAIN
      - NGINX_OVERRIDE_PROTOCOL=HTTP,$SITE_DOMAIN
      - DRUSH_OPTIONS_URI=https://$SITE_DOMAIN
      - DRUPAL_DB_DATABASE=$MYSQL_DB
      - DRUPAL_DB_USERNAME=$MYSQL_USER
      - DRUPAL_DB_PASSWORD=$MYSQL_PASS
      - DRUPAL_DB_HOST=mysql
      - DRUPAL_DB_DRIVER=mysql
      - PHP_ENVIRONMENT=dev
      - PHP_XDEBUG=true
      # Rate limiting.
      - NGINX_LIMIT_HUMANS=1024r/s
      - NGINX_BURST_HUMANS=1024
      # Local proxy.
      - VIRTUAL_HOST=$SITE_DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=${PROXY:-proxy}
      - HTTPS_METHOD=noredirect
    labels:
      caddy: $SITE_DOMAIN
      caddy.reverse_proxy: "{{upstreams}}"
    networks:
      - default
      - proxy
