<?php

/**
 * @file
 * Defines a simple telephone number field type with a "type" sub-field.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function telephone_type_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.telephone_type':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Telephone type module allows you to create fields that contain telephone numbers with telephone types (ex: Work cell). See the <a href=":field">Field module help</a> and the <a href=":field_ui">Field UI help</a> pages for general information on fields and how to create and manage them. For more information, see the <a href=":documentation">online documentation for the Telephone module</a>.', [
        ':field' => Url::fromRoute('help.page', [
          'name' => 'field',
        ])->toString(),
        ':field_ui' => (\Drupal::moduleHandler()->moduleExists('field_ui')) ? Url::fromRoute('help.page', [
          'name' => 'field_ui',
        ])->toString() : '#',
        ':documentation' => 'https://www.drupal.org/documentation/modules/telephone_type',
      ]) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Managing and displaying telephone fields') . '</dt>';
      $output .= '<dd>' . t('The <em>settings</em> and the <em>display</em> of the telephone field can be configured separately. See the <a href=":field_ui">Field UI help</a> for more information on how to manage fields and their display.', [
        ':field_ui' => (\Drupal::moduleHandler()->moduleExists('field_ui')) ? Url::fromRoute('help.page', [
          'name' => 'field_ui',
        ])->toString() : '#',
      ]) . '</dd>';
      $output .= '<dt>' . t('Displaying telephone numbers as links') . '</dt>';
      $output .= '<dd>' . t('Telephone numbers can be displayed as links with the scheme name <em>tel:</em> by choosing the <em>Telephone type link</em> display format on the <em>Manage display</em> page. Any spaces will be stripped out of the link text. This semantic markup improves the user experience on mobile and assistive technology devices.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
