<?php

/**
 * @file
 * Themes and preprocessors for the paragraphs page title module.
 */

/**
 * Implements hook_preprocess_paragraph().
 *
 * @todo Do we need to set a cache context on the URL?
 */
function paragraphs_page_title_preprocess_paragraph__page_title(&$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
  // When editing a content type using a page title paragraph, the page title
  // is not available. Also to avoid "synchonisation" issue when updating the
  // content type title field (if any) and the paragraph preview, we use a
  // placeholder.
  $variables['title'] = $title ?? t('Page title placeholder');
}

/**
 * Implements hook_theme().
 */
function paragraphs_page_title_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__page_title' => [
      'base hook' => 'paragraph',
    ],
  ];
}
