<?php

/**
 * @file
 * Themes and preprocessors for the paragraphs page title module.
 */

/**
 * Implements hook_preprocess_paragraph__page_title().
 *
 * @todo Do we need to set a cache context on the URL?
 */
function paragraphs_page_title_preprocess_paragraph__page_title(&$variables) {
  // If we are in a form, then the '#id' will be set. In that case, we don't
  // want to show the page title as it would not be updated when changing the
  // title field. We will display a placeholder instead.
  if (!isset($variables['elements']['#id'])) {
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
  }

  // Placeholder title if we are in a form or couldn't resolve the title.
  if (empty($title)) {
    $title = t('Page title placeholder');
  }

  // We use the page_title type for the render array for consistency with
  // how the page title block is rendered.
  $variables['content']['title'] = [
    '#type' => 'page_title',
    '#title' => $title ?? t('Page title placeholder'),
  ];
}

/**
 * Implements hook_theme().
 */
function paragraphs_page_title_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__page_title' => [
      'base hook' => 'paragraph',
    ],
  ];
}
