module:
  admin_denied: 0
  allowed_formats: 0
  bcc: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  contextual: 0
  ctools: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  layout_builder: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  linked_responsive_image_media_formatter: 0
  maintenance200: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  node: 0
  page_cache: 0
  paragraphs_page_title: 0
  paragraphs_viewmode: 0
  path: 0
  path_alias: 0
  r4032login: 0
  redirect: 0
  responsive_image: 0
  seckit: 0
  slt_access: 0
  slt_contacts: 0
  slt_general: 0
  slt_layouts: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  telephone_type: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  common_design: 0
  common_design_subtheme: 0
  seven: 0
  common_design_admin_subtheme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
