base_url: 'https://auth.humanitarian.id'
auto_redirect: true
disable_default: true
_core:
  default_config_hash: ZT0ACgdXm4m65rwBVtAR0TGxX6QsMptRkbldivu-7yI
client_id: HID_CLIENT_ID_DO_NOT_COMMIT_TO_REPOSITORY
client_secret: HID_CLIENT_SECRET_DO_NOT_COMMIT_TO_REPOSITORY
