- entity: 'node'
  nid: 100
  type: 'public_page'
  title: '404'
  status: 1
  path:
    - alias: '/404'
      pathauto: false
  body:
    - format: "filtered_html"
      value: |
        <p>Page not found</p>
        <p>Sorry, the page you are looking for could not be found.</p>
        <p>Please check the URL, or go back to our homepage.</p>
        <p><a href="/">Back to Homepage</a></p>
