- entity: 'node'
  nid: 200
  type: 'public_page'
  title: 'Welcome to OCHA Donor Support Group'
  status: 1
  path:
    - alias: '/welcome'
      pathauto: false
  body:
    - format: "filtered_html"
      value: |
        <p>Welcome to the website of the OCHA Donor Support Group. We are excited to announce that you will be able to access the site using Humanitarian ID (HID) - a unique authentication and contact management system designed especially for the humanitarian community.</p>
        <p>All current ODSG Partners are invited to login to visit the member site, where they will find all materials and resources related to the OCHA Donor Support Group.</p>
  layout_builder__layout:
    - '#process':
        callback: 'section'
        args:
          layout_id: layout_onecol
          layout_settings: {  }
          components:
            - region: content
              configuration:
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                id: 'field_block:node:public_page:body'
                formatter:
                  label: hidden
                  type: text_default
                  settings: {  }
                  third_party_settings: {  }
              additional: {  }
              weight: 0
            - region: content
              configuration:
                label_display: '1'
                label: Login with Humanitarian ID
                context_mapping: {  }
                id: social_auth_login
                provider: block
              additional: {  }
              weight: 1
          third_party_settings: {  }
