name: Run Composer Update

on:
  schedule:
    - cron: '35 6 * * 4'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Update The Thing
      id: update-action
      uses: UN-OCHA/actions/composer-update@OPS-10254-config-too
      with:
        aws_access_key_id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        github_access_token: ${{ secrets.PAT }}
        patch_branch: 'develop'
        patch_maintainers: ${{ secrets.DRUPAL_MAINTAINERS }}
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel_name: ${{ vars.SLACK_CHANNEL }}
